# Generated by Django 4.0.6 on 2022-08-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='user_type',
        ),
    ]
