# Generated by Django 4.0.6 on 2022-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_theatersignup_usersignup_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatersignup',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
