# Generated by Django 4.0.6 on 2022-08-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_theatersignup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatersignup',
            name='licenseno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
