# Generated by Django 4.0.6 on 2022-08-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_theatersignup_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatersignup',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
