# Generated by Django 4.0.6 on 2022-08-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_feedbackk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatersignup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='theatre_image'),
        ),
    ]
