# Generated by Django 4.0.6 on 2022-08-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='contactus',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
        migrations.AddField(
            model_name='contactus',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='pho',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
