# Generated by Django 4.0.6 on 2022-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_contactus_contactus_remove_contactus_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
