# Generated by Django 4.0.6 on 2022-08-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_moviename'),
        ('user', '0002_alter_moviereview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movies'),
            preserve_default=False,
        ),
    ]
