# Generated by Django 4.0.6 on 2022-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_seat_moviebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebooking',
            name='seats',
            field=models.TextField(blank=True, null=True),
        ),
    ]
