# Generated by Django 4.0.6 on 2022-08-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_moviebooking_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebooking',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
