# Generated by Django 4.0.6 on 2022-08-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_remove_theatersignup_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(blank=True, max_length=20, null=True)),
                ('movieimage', models.ImageField(blank=True, null=True, upload_to='movieimage')),
                ('show1', models.CharField(blank=True, max_length=20, null=True)),
                ('show2', models.CharField(blank=True, max_length=20, null=True)),
                ('show3', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('gener', models.CharField(blank=True, max_length=100, null=True)),
                ('cast_crew', models.CharField(blank=True, max_length=200, null=True)),
                ('theater_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.theatersignup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
