# Generated by Django 4.0.6 on 2022-08-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='gener',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
