# Generated by Django 4.0.6 on 2022-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_gener_movies_genre_movies_status_movies_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='moviename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
