# Generated by Django 4.0.6 on 2022-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
