# Generated by Django 4.0.6 on 2022-08-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_feedbackk_user'),
        ('movies', '0005_movies_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='theater_owner',
        ),
        migrations.AddField(
            model_name='rating',
            name='user_signup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.usersignup'),
        ),
    ]
